# Generated by Django 4.2.4 on 2025-09-18 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("keywords", models.JSONField(default=list)),
                ("sources", models.JSONField(default=list)),
                ("exclude_keywords", models.JSONField(default=list)),
                ("schedule_enabled", models.BooleanField(default=True)),
                ("schedule_interval", models.IntegerField(default=3600)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "daily_budget",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
                (
                    "current_spend",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("reddit", "Reddit"),
                            ("discord", "Discord"),
                            ("forum", "Forum"),
                            ("website", "Website"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("rate_limit", models.IntegerField(default=60)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sources",
                "unique_together": {("source_type", "url")},
            },
        ),
        migrations.CreateModel(
            name="RawContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("title", models.CharField(blank=True, max_length=500)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("published_at", models.DateTimeField()),
                ("content", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("is_processed", models.BooleanField(default=False)),
                ("is_valid", models.BooleanField(default=True)),
                ("echo_score", models.FloatField(blank=True, null=True)),
                ("depth_score", models.FloatField(blank=True, null=True)),
                ("diversity_score", models.FloatField(blank=True, null=True)),
                ("recency_score", models.FloatField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_content",
                        to="common.campaign",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_content",
                        to="common.source",
                    ),
                ),
            ],
            options={
                "db_table": "raw_content",
                "ordering": ["-published_at"],
                "unique_together": {("source", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="ProcessedContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cleaned_content", models.TextField()),
                ("language", models.CharField(default="en", max_length=10)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("toxicity_score", models.FloatField(blank=True, null=True)),
                ("spam_score", models.FloatField(blank=True, null=True)),
                ("keywords", models.JSONField(default=list)),
                ("entities", models.JSONField(default=dict)),
                ("topics", models.JSONField(default=list)),
                ("processing_version", models.CharField(default="1.0", max_length=50)),
                ("processing_time", models.DurationField(blank=True, null=True)),
                (
                    "raw_content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed",
                        to="common.rawcontent",
                    ),
                ),
            ],
            options={
                "db_table": "processed_content",
            },
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("pain_point", "Pain Point"),
                            ("praise", "Praise"),
                            ("feature_request", "Feature Request"),
                            ("competitor_mention", "Competitor Mention"),
                            ("trend", "Trend"),
                            ("influencer", "Influencer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("summary", models.TextField(blank=True)),
                ("confidence_score", models.FloatField()),
                ("impact_score", models.FloatField(blank=True, null=True)),
                ("priority_score", models.FloatField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                ("is_validated", models.BooleanField(default=False)),
                ("user_rating", models.IntegerField(blank=True, null=True)),
                ("user_feedback", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="common.campaign",
                    ),
                ),
                (
                    "content",
                    models.ManyToManyField(
                        related_name="insights", to="common.processedcontent"
                    ),
                ),
            ],
            options={
                "db_table": "insights",
                "ordering": ["-priority_score", "-confidence_score"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("campaign_created", "Campaign Created"),
                            ("campaign_updated", "Campaign Updated"),
                            ("content_scraped", "Content Scraped"),
                            ("content_processed", "Content Processed"),
                            ("insight_generated", "Insight Generated"),
                            ("user_action", "User Action"),
                            ("agent_action", "Agent Action"),
                            ("error", "Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("action_description", models.TextField()),
                ("agent_name", models.CharField(blank=True, max_length=100)),
                ("model_version", models.CharField(blank=True, max_length=50)),
                ("prompt_hash", models.CharField(blank=True, max_length=64)),
                ("execution_time", models.DurationField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("error_details", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.campaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Influencer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=255)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("source_type", models.CharField(max_length=20)),
                ("profile_url", models.URLField(blank=True)),
                ("follower_count", models.IntegerField(blank=True, null=True)),
                ("engagement_rate", models.FloatField(blank=True, null=True)),
                ("influence_score", models.FloatField()),
                ("post_frequency", models.FloatField(blank=True, null=True)),
                ("avg_likes", models.FloatField(blank=True, null=True)),
                ("avg_comments", models.FloatField(blank=True, null=True)),
                ("content_topics", models.JSONField(default=list)),
                ("sentiment_distribution", models.JSONField(default=dict)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influencers",
                        to="common.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "influencers",
                "ordering": ["-influence_score"],
                "unique_together": {("campaign", "username", "source_type")},
            },
        ),
        migrations.CreateModel(
            name="AgentMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("agent_name", models.CharField(max_length=100)),
                ("execution_time", models.DurationField()),
                ("success_rate", models.FloatField()),
                ("error_count", models.IntegerField(default=0)),
                ("cpu_usage", models.FloatField(blank=True, null=True)),
                ("memory_usage", models.FloatField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("accuracy_score", models.FloatField(blank=True, null=True)),
                ("precision_score", models.FloatField(blank=True, null=True)),
                ("recall_score", models.FloatField(blank=True, null=True)),
                ("metric_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "agent_metrics",
                "ordering": ["-metric_date"],
                "unique_together": {("agent_name", "metric_date", "campaign")},
            },
        ),
    ]
