# Generated by Django 4.2.4 on 2025-09-19 12:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("reddit", "Reddit"),
                            ("discord", "Discord"),
                            ("tiktok", "TikTok"),
                            ("forum", "Forum"),
                            ("twitter", "Twitter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("member_count", models.IntegerField(default=0)),
                ("echo_score", models.FloatField(default=0.0)),
                ("echo_score_change", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=True)),
                ("last_analyzed", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("language", models.CharField(default="en", max_length=10)),
            ],
            options={
                "verbose_name_plural": "Communities",
                "db_table": "communities",
                "ordering": ["-echo_score"],
                "unique_together": {("platform", "name")},
            },
        ),
        migrations.CreateModel(
            name="PainPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("keyword", models.CharField(max_length=100)),
                ("mention_count", models.IntegerField(default=0)),
                ("growth_percentage", models.FloatField(default=0.0)),
                ("sentiment_score", models.FloatField(default=0.0)),
                ("heat_level", models.IntegerField(default=1)),
                ("example_content", models.TextField(blank=True)),
                ("related_keywords", models.JSONField(default=list)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pain_points",
                        to="common.campaign",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pain_points",
                        to="common.community",
                    ),
                ),
            ],
            options={
                "db_table": "pain_points",
                "ordering": ["-growth_percentage", "-mention_count"],
                "unique_together": {("keyword", "campaign", "community")},
            },
        ),
        migrations.AddField(
            model_name="influencer",
            name="karma_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="influencer",
            name="last_active",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="influencer",
            name="reach",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="influencer",
            name="topics",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="influencer",
            name="engagement_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="influencer",
            name="influence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="influencer",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="influencers",
                to="common.community",
            ),
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("thread_id", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                ("author", models.CharField(max_length=100)),
                ("author_karma", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("upvotes", models.IntegerField(default=0)),
                ("downvotes", models.IntegerField(default=0)),
                ("echo_score", models.FloatField(default=0.0)),
                ("sentiment_score", models.FloatField(default=0.0)),
                ("llm_summary", models.TextField(blank=True)),
                ("token_count", models.IntegerField(default=0)),
                (
                    "processing_cost",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
                ),
                ("published_at", models.DateTimeField()),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                ("engagement_rate", models.FloatField(default=0.0)),
                ("controversy_score", models.FloatField(default=0.0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="common.campaign",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="common.community",
                    ),
                ),
                (
                    "influencers_mentioned",
                    models.ManyToManyField(blank=True, to="common.influencer"),
                ),
                (
                    "pain_points",
                    models.ManyToManyField(blank=True, to="common.painpoint"),
                ),
            ],
            options={
                "db_table": "threads",
                "ordering": ["-published_at"],
                "unique_together": {("thread_id", "community")},
            },
        ),
        migrations.CreateModel(
            name="DashboardMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("active_campaigns", models.IntegerField(default=0)),
                ("high_echo_communities", models.IntegerField(default=0)),
                ("high_echo_change_percent", models.FloatField(default=0.0)),
                ("new_pain_points_above_50", models.IntegerField(default=0)),
                ("new_pain_points_change", models.IntegerField(default=0)),
                ("positivity_ratio", models.FloatField(default=0.0)),
                ("positivity_change_pp", models.FloatField(default=0.0)),
                ("llm_tokens_used", models.IntegerField(default=0)),
                ("llm_cost_usd", models.FloatField(default=0.0)),
                ("total_threads_analyzed", models.IntegerField(default=0)),
                ("total_communities_tracked", models.IntegerField(default=0)),
                ("total_influencers_identified", models.IntegerField(default=0)),
                ("sentiment_average", models.FloatField(default=0.0)),
                ("echo_score_average", models.FloatField(default=0.0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_metrics",
                        to="common.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_metrics",
                "ordering": ["-date"],
                "unique_together": {("date", "campaign")},
            },
        ),
    ]
