# Generated by Django 4.2.4 on 2025-09-19 13:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_dashboard_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("headquarters", models.CharField(blank=True, max_length=255)),
                ("social_handles", models.JSONField(default=dict)),
                ("primary_keywords", models.JSONField(default=list)),
                ("product_keywords", models.JSONField(default=list)),
                ("exclude_keywords", models.JSONField(default=list)),
                ("sources", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "brands",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="common.brand",
            ),
        ),
        migrations.CreateModel(
            name="Competitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("keywords", models.JSONField(default=list)),
                ("social_handles", models.JSONField(default=dict)),
                ("market_share_estimate", models.FloatField(blank=True, null=True)),
                ("sentiment_comparison", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitors",
                        to="common.brand",
                    ),
                ),
            ],
            options={
                "db_table": "competitors",
                "ordering": ["name"],
                "unique_together": {("brand", "name")},
            },
        ),
    ]
