# Generated by Django 5.2.7 on 2025-10-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_brand_campaign_brand_competitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
