# Generated by Django 5.2.7 on 2025-10-22 10:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_source_category_source_description_source_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='influencer',
            name='advocacy_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='authority_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='avg_engagement_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='avg_post_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='common.brand'),
        ),
        migrations.AddField(
            model_name='influencer',
            name='brand_mention_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='brand_mention_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='communities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='influencer',
            name='first_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='influencer',
            name='platform',
            field=models.CharField(default='reddit', max_length=50),
        ),
        migrations.AddField(
            model_name='influencer',
            name='reach_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='relevance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='sample_thread_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='influencer',
            name='sentiment_towards_brand',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='total_karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencer',
            name='total_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='post_frequency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='influencer',
            index=models.Index(fields=['brand', '-relevance_score'], name='influencers_brand_i_970629_idx'),
        ),
        migrations.AddIndex(
            model_name='influencer',
            index=models.Index(fields=['campaign', '-influence_score'], name='influencers_campaig_4c4c25_idx'),
        ),
        migrations.AddIndex(
            model_name='influencer',
            index=models.Index(fields=['platform', '-reach_score'], name='influencers_platfor_6f007d_idx'),
        ),
    ]
