# Generated by Django 5.2.7 on 2025-10-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_add_campaign_completion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_campaign_interval', models.IntegerField(default=3600, help_text='Schedule interval for custom campaigns in seconds')),
                ('auto_campaign_interval', models.IntegerField(default=3600, help_text='Schedule interval for automatic brand analytics campaigns in seconds')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
    ]
