# Generated by Django 5.2.7 on 2025-10-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_add_system_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='collection_weeks',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='campaign',
            name='monitored_communities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='community',
            name='activity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='community',
            name='avg_engagement_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='community',
            name='echo_score_delta',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='community',
            name='threads_last_4_weeks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='painpoint',
            name='week_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='week_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
