# Generated by Django 5.2.7 on 2025-10-31 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_campaign_collection_weeks_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='community',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('automatic', 'Automatic Brand Analytics'), ('custom', 'Custom Campaign')], default='custom', help_text='Type of campaign: automatic (Brand Analytics) or custom (user-created)', max_length=20),
        ),
        migrations.AddField(
            model_name='community',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand this community is tracked for (for Brand Analytics separation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='common.brand'),
        ),
        migrations.AddField(
            model_name='community',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Campaign this community is tracked for (for data separation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communities', to='common.campaign'),
        ),
        migrations.AddField(
            model_name='painpoint',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand this pain point is tracked for (for Brand Analytics separation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pain_points', to='common.brand'),
        ),
        migrations.AddField(
            model_name='thread',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand this thread is tracked for (for Brand Analytics separation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='common.brand'),
        ),
        migrations.AlterUniqueTogether(
            name='community',
            unique_together={('platform', 'name', 'campaign')},
        ),
    ]
