# Generated by Django 5.2.7 on 2025-11-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_monthly_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='activity_score',
        ),
        migrations.RemoveField(
            model_name='community',
            name='avg_engagement_rate',
        ),
        migrations.RemoveField(
            model_name='community',
            name='echo_score_change',
        ),
        migrations.RemoveField(
            model_name='community',
            name='echo_score_delta',
        ),
        migrations.RemoveField(
            model_name='community',
            name='threads_last_4_weeks',
        ),
        migrations.AddField(
            model_name='community',
            name='influencer_engagement',
            field=models.IntegerField(default=0, help_text='Total engagement on key influencer posts'),
        ),
        migrations.AddField(
            model_name='community',
            name='influencer_post_count',
            field=models.IntegerField(default=0, help_text='Number of posts by key influencer'),
        ),
        migrations.AddField(
            model_name='community',
            name='key_influencer',
            field=models.CharField(blank=True, help_text='Most active/influential author in this community', max_length=200, null=True),
        ),
    ]
