# Generated by Django 5.2.7 on 2025-11-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0017_fix_unique_constraint_per_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Direct link to the thread/post",
                max_length=500,
                null=True,
            ),
        ),
    ]
