# Generated by Django 5.2.7 on 2025-11-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_add_thread_url_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="author",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="thread",
            name="thread_id",
            field=models.CharField(max_length=255),
        ),
    ]
