# Generated by Django 5.2.7 on 2025-11-02 04:17

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0019_alter_thread_author_alter_thread_thread_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
        migrations.AddField(
            model_name="thread",
            name="embedding_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="thread",
            name="embedding_model",
            field=models.CharField(default="text-embedding-3-small", max_length=100),
        ),
    ]
