# Generated by Django 5.2.7 on 2025-11-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_add_thread_embeddings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='insight_type',
            field=models.CharField(choices=[('pain_point', 'Pain Point'), ('praise', 'Praise'), ('feature_request', 'Feature Request'), ('competitor_mention', 'Competitor Mention'), ('trend', 'Trend'), ('influencer', 'Influencer'), ('strategic_report', 'Strategic Report')], max_length=30),
        ),
    ]
